name: "Build SQLite3 WASM"
description: "Build SQLite3 WASM on macOS"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.x"
        channel: "stable"
    - name: Setup macOS
      shell: bash
      run: |
        brew install cmake
        brew install llvm@18
        brew install binaryen
        curl -sL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-22/libclang_rt.builtins-wasm32-wasi-22.0.tar.gz | \
        tar x -zf - -C /opt/homebrew/opt/llvm@18/lib/clang/18*
        curl -sS -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-22/wasi-sysroot-22.0.tar.gz | \
        sudo tar x -zf - -C /opt
    - name: Install Rust Nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2024-05-18
        components: rust-src
    - name: Set environment variable
      shell: bash
      run: |
        echo "/opt/homebrew/opt/llvm@18/bin" >> $GITHUB_PATH
    - name: Flutter pub get
      working-directory: sqlite3
      shell: bash
      run: |
        flutter pub get
    - name: Compile sqlite3.wasm on macOS
      if: runner.os == 'macOS'
      working-directory: sqlite3
      shell: bash
      run: |
        cmake -Dwasi_sysroot=/opt/wasi-sysroot -Dclang=/opt/homebrew/opt/llvm@18/bin/clang -S assets/wasm -B .dart_tool/sqlite3_build
        cmake --build .dart_tool/sqlite3_build/ -t output -j
