name: Build and upload SQLite3 WASM

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-powersync.[0-9]+"

jobs:
  compile_sqlite3_wasm:
    strategy:
      matrix:
        os: [macos-latest]

    name: Compile sqlite3 wasm for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build wasm
        uses: ./.github/actions/build-wasm
      - name: Upload sqlite3 binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          file: sqlite3/.dart_tool/sqlite3_build/sqlite3.wasm
          asset_name: sqlite3.wasm
          body: "PowerSync SQLite3 WASM binary"
          tag: ${{ github.ref_name }}
      - name: Upload sqlite3 debug binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          file: sqlite3/.dart_tool/sqlite3_build/sqlite3.debug.wasm
          asset_name: sqlite3.debug.wasm
          tag: ${{ github.ref_name }}
